server:
  port: 8081
# yml配置负载均衡策略
stock-server: # 被调用的微服务名
  ribbon:
    # 指定使用Nacos提供的负载均衡策略（优先调用同一集群的实例，基于随机&权重）
    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    # 自定义的负载均衡策略（基于随机&权重）
    #NFLoadBalancerRuleClassName: org.example.ribbon.CustomRibbonRuleConfig
spring:
  application:
    name: order-server    # 配置 Nacos server 的地址
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848   # nacos服务器IP和端口号
      discovery:
        username: nacos   # nacos服务器用户名
        password: nacos   # nacos服务器密码
        namespace: public